server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache assets agressif (JS/CSS/WASM hachés par Angular)
    location ~* \.(js|css|wasm)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Pas de cache sur index.html
    location = /index.html {
        add_header Cache-Control "no-cache";
    }
}
