import { ElementData } from '../models';

export const ELEMENTS: ElementData[] = [
  { atomicNumber: 1,  symbol: 'H',  name: 'Hydrogen',      cpkColor: '#FFFFFF', valences: [1],          covalentRadius: 0.31, atomicMass: 1.008,   electronegativity: 2.20, category: 'nonmetal' },
  { atomicNumber: 2,  symbol: 'He', name: 'Helium',         cpkColor: '#D9FFFF', valences: [0],          covalentRadius: 0.28, atomicMass: 4.003,   electronegativity: null, category: 'noble-gas' },
  { atomicNumber: 3,  symbol: 'Li', name: 'Lithium',        cpkColor: '#CC80FF', valences: [1],          covalentRadius: 1.28, atomicMass: 6.941,   electronegativity: 0.98, category: 'alkali-metal' },
  { atomicNumber: 4,  symbol: 'Be', name: 'Beryllium',      cpkColor: '#C2FF00', valences: [2],          covalentRadius: 0.96, atomicMass: 9.012,   electronegativity: 1.57, category: 'alkaline-earth' },
  { atomicNumber: 5,  symbol: 'B',  name: 'Boron',          cpkColor: '#FFB5B5', valences: [3],          covalentRadius: 0.84, atomicMass: 10.811,  electronegativity: 2.04, category: 'metalloid' },
  { atomicNumber: 6,  symbol: 'C',  name: 'Carbon',         cpkColor: '#909090', valences: [4],          covalentRadius: 0.77, atomicMass: 12.011,  electronegativity: 2.55, category: 'nonmetal' },
  { atomicNumber: 7,  symbol: 'N',  name: 'Nitrogen',       cpkColor: '#3050F8', valences: [3],          covalentRadius: 0.75, atomicMass: 14.007,  electronegativity: 3.04, category: 'nonmetal' },
  { atomicNumber: 8,  symbol: 'O',  name: 'Oxygen',         cpkColor: '#FF0D0D', valences: [2],          covalentRadius: 0.73, atomicMass: 15.999,  electronegativity: 3.44, category: 'nonmetal' },
  { atomicNumber: 9,  symbol: 'F',  name: 'Fluorine',       cpkColor: '#90E050', valences: [1],          covalentRadius: 0.71, atomicMass: 18.998,  electronegativity: 3.98, category: 'halogen' },
  { atomicNumber: 10, symbol: 'Ne', name: 'Neon',           cpkColor: '#B3E3F5', valences: [0],          covalentRadius: 0.58, atomicMass: 20.180,  electronegativity: null, category: 'noble-gas' },
  { atomicNumber: 11, symbol: 'Na', name: 'Sodium',         cpkColor: '#AB5CF2', valences: [1],          covalentRadius: 1.66, atomicMass: 22.990,  electronegativity: 0.93, category: 'alkali-metal' },
  { atomicNumber: 12, symbol: 'Mg', name: 'Magnesium',      cpkColor: '#8AFF00', valences: [2],          covalentRadius: 1.41, atomicMass: 24.305,  electronegativity: 1.31, category: 'alkaline-earth' },
  { atomicNumber: 13, symbol: 'Al', name: 'Aluminum',       cpkColor: '#BFA6A6', valences: [3],          covalentRadius: 1.21, atomicMass: 26.982,  electronegativity: 1.61, category: 'post-transition-metal' },
  { atomicNumber: 14, symbol: 'Si', name: 'Silicon',        cpkColor: '#F0C8A0', valences: [4],          covalentRadius: 1.11, atomicMass: 28.086,  electronegativity: 1.90, category: 'metalloid' },
  { atomicNumber: 15, symbol: 'P',  name: 'Phosphorus',     cpkColor: '#FF8000', valences: [3, 5],       covalentRadius: 1.07, atomicMass: 30.974,  electronegativity: 2.19, category: 'nonmetal' },
  { atomicNumber: 16, symbol: 'S',  name: 'Sulfur',         cpkColor: '#FFFF30', valences: [2, 4, 6],    covalentRadius: 1.05, atomicMass: 32.065,  electronegativity: 2.58, category: 'nonmetal' },
  { atomicNumber: 17, symbol: 'Cl', name: 'Chlorine',       cpkColor: '#1FF01F', valences: [1],          covalentRadius: 1.02, atomicMass: 35.453,  electronegativity: 3.16, category: 'halogen' },
  { atomicNumber: 18, symbol: 'Ar', name: 'Argon',          cpkColor: '#80D1E3', valences: [0],          covalentRadius: 1.06, atomicMass: 39.948,  electronegativity: null, category: 'noble-gas' },
  { atomicNumber: 19, symbol: 'K',  name: 'Potassium',      cpkColor: '#8F40D4', valences: [1],          covalentRadius: 2.03, atomicMass: 39.098,  electronegativity: 0.82, category: 'alkali-metal' },
  { atomicNumber: 20, symbol: 'Ca', name: 'Calcium',        cpkColor: '#3DFF00', valences: [2],          covalentRadius: 1.76, atomicMass: 40.078,  electronegativity: 1.00, category: 'alkaline-earth' },
  { atomicNumber: 21, symbol: 'Sc', name: 'Scandium',       cpkColor: '#E6E6E6', valences: [3],          covalentRadius: 1.70, atomicMass: 44.956,  electronegativity: 1.36, category: 'transition-metal' },
  { atomicNumber: 22, symbol: 'Ti', name: 'Titanium',       cpkColor: '#BFC2C7', valences: [4],          covalentRadius: 1.60, atomicMass: 47.867,  electronegativity: 1.54, category: 'transition-metal' },
  { atomicNumber: 23, symbol: 'V',  name: 'Vanadium',       cpkColor: '#A6A6AB', valences: [5],          covalentRadius: 1.53, atomicMass: 50.942,  electronegativity: 1.63, category: 'transition-metal' },
  { atomicNumber: 24, symbol: 'Cr', name: 'Chromium',       cpkColor: '#8A99C7', valences: [6],          covalentRadius: 1.39, atomicMass: 51.996,  electronegativity: 1.66, category: 'transition-metal' },
  { atomicNumber: 25, symbol: 'Mn', name: 'Manganese',      cpkColor: '#9C7AC7', valences: [2, 4, 7],    covalentRadius: 1.61, atomicMass: 54.938,  electronegativity: 1.55, category: 'transition-metal' },
  { atomicNumber: 26, symbol: 'Fe', name: 'Iron',           cpkColor: '#E06633', valences: [2, 3],       covalentRadius: 1.52, atomicMass: 55.845,  electronegativity: 1.83, category: 'transition-metal' },
  { atomicNumber: 27, symbol: 'Co', name: 'Cobalt',         cpkColor: '#F090A0', valences: [2, 3],       covalentRadius: 1.50, atomicMass: 58.933,  electronegativity: 1.88, category: 'transition-metal' },
  { atomicNumber: 28, symbol: 'Ni', name: 'Nickel',         cpkColor: '#50D050', valences: [2],          covalentRadius: 1.24, atomicMass: 58.693,  electronegativity: 1.91, category: 'transition-metal' },
  { atomicNumber: 29, symbol: 'Cu', name: 'Copper',         cpkColor: '#C88033', valences: [1, 2],       covalentRadius: 1.38, atomicMass: 63.546,  electronegativity: 1.90, category: 'transition-metal' },
  { atomicNumber: 30, symbol: 'Zn', name: 'Zinc',           cpkColor: '#7D80B0', valences: [2],          covalentRadius: 1.31, atomicMass: 65.38,   electronegativity: 1.65, category: 'transition-metal' },
  { atomicNumber: 31, symbol: 'Ga', name: 'Gallium',        cpkColor: '#C28F8F', valences: [3],          covalentRadius: 1.22, atomicMass: 69.723,  electronegativity: 1.81, category: 'post-transition-metal' },
  { atomicNumber: 32, symbol: 'Ge', name: 'Germanium',      cpkColor: '#668F8F', valences: [4],          covalentRadius: 1.22, atomicMass: 72.630,  electronegativity: 2.01, category: 'metalloid' },
  { atomicNumber: 33, symbol: 'As', name: 'Arsenic',        cpkColor: '#BD80E3', valences: [3, 5],       covalentRadius: 1.19, atomicMass: 74.922,  electronegativity: 2.18, category: 'metalloid' },
  { atomicNumber: 34, symbol: 'Se', name: 'Selenium',       cpkColor: '#FFA100', valences: [2, 4, 6],    covalentRadius: 1.20, atomicMass: 78.971,  electronegativity: 2.55, category: 'nonmetal' },
  { atomicNumber: 35, symbol: 'Br', name: 'Bromine',        cpkColor: '#A62929', valences: [1],          covalentRadius: 1.20, atomicMass: 79.904,  electronegativity: 2.96, category: 'halogen' },
  { atomicNumber: 36, symbol: 'Kr', name: 'Krypton',        cpkColor: '#5CB8D1', valences: [0],          covalentRadius: 1.16, atomicMass: 83.798,  electronegativity: 3.00, category: 'noble-gas' },
  { atomicNumber: 37, symbol: 'Rb', name: 'Rubidium',       cpkColor: '#702EB0', valences: [1],          covalentRadius: 2.20, atomicMass: 85.468,  electronegativity: 0.82, category: 'alkali-metal' },
  { atomicNumber: 38, symbol: 'Sr', name: 'Strontium',      cpkColor: '#00FF00', valences: [2],          covalentRadius: 1.95, atomicMass: 87.62,   electronegativity: 0.95, category: 'alkaline-earth' },
  { atomicNumber: 39, symbol: 'Y',  name: 'Yttrium',        cpkColor: '#94FFFF', valences: [3],          covalentRadius: 1.90, atomicMass: 88.906,  electronegativity: 1.22, category: 'transition-metal' },
  { atomicNumber: 40, symbol: 'Zr', name: 'Zirconium',      cpkColor: '#94E0E0', valences: [4],          covalentRadius: 1.75, atomicMass: 91.224,  electronegativity: 1.33, category: 'transition-metal' },
  { atomicNumber: 41, symbol: 'Nb', name: 'Niobium',        cpkColor: '#73C2C9', valences: [5],          covalentRadius: 1.64, atomicMass: 92.906,  electronegativity: 1.60, category: 'transition-metal' },
  { atomicNumber: 42, symbol: 'Mo', name: 'Molybdenum',     cpkColor: '#54B5B5', valences: [6],          covalentRadius: 1.54, atomicMass: 95.95,   electronegativity: 2.16, category: 'transition-metal' },
  { atomicNumber: 43, symbol: 'Tc', name: 'Technetium',     cpkColor: '#3B9E9E', valences: [7],          covalentRadius: 1.47, atomicMass: 98.0,    electronegativity: 1.90, category: 'transition-metal' },
  { atomicNumber: 44, symbol: 'Ru', name: 'Ruthenium',      cpkColor: '#248F8F', valences: [4],          covalentRadius: 1.46, atomicMass: 101.07,  electronegativity: 2.20, category: 'transition-metal' },
  { atomicNumber: 45, symbol: 'Rh', name: 'Rhodium',        cpkColor: '#0A7D8C', valences: [3],          covalentRadius: 1.42, atomicMass: 102.906, electronegativity: 2.28, category: 'transition-metal' },
  { atomicNumber: 46, symbol: 'Pd', name: 'Palladium',      cpkColor: '#006985', valences: [4],          covalentRadius: 1.39, atomicMass: 106.42,  electronegativity: 2.20, category: 'transition-metal' },
  { atomicNumber: 47, symbol: 'Ag', name: 'Silver',         cpkColor: '#C0C0C0', valences: [1],          covalentRadius: 1.45, atomicMass: 107.868, electronegativity: 1.93, category: 'transition-metal' },
  { atomicNumber: 48, symbol: 'Cd', name: 'Cadmium',        cpkColor: '#FFD98F', valences: [2],          covalentRadius: 1.44, atomicMass: 112.414, electronegativity: 1.69, category: 'transition-metal' },
  { atomicNumber: 49, symbol: 'In', name: 'Indium',         cpkColor: '#A67573', valences: [3],          covalentRadius: 1.42, atomicMass: 114.818, electronegativity: 1.78, category: 'post-transition-metal' },
  { atomicNumber: 50, symbol: 'Sn', name: 'Tin',            cpkColor: '#668080', valences: [4],          covalentRadius: 1.39, atomicMass: 118.710, electronegativity: 1.96, category: 'post-transition-metal' },
  { atomicNumber: 51, symbol: 'Sb', name: 'Antimony',       cpkColor: '#9E63B5', valences: [3, 5],       covalentRadius: 1.39, atomicMass: 121.760, electronegativity: 2.05, category: 'metalloid' },
  { atomicNumber: 52, symbol: 'Te', name: 'Tellurium',      cpkColor: '#D47A00', valences: [2, 4, 6],    covalentRadius: 1.38, atomicMass: 127.60,  electronegativity: 2.10, category: 'metalloid' },
  { atomicNumber: 53, symbol: 'I',  name: 'Iodine',         cpkColor: '#940094', valences: [1],          covalentRadius: 1.39, atomicMass: 126.904, electronegativity: 2.66, category: 'halogen' },
  { atomicNumber: 54, symbol: 'Xe', name: 'Xenon',          cpkColor: '#429EB0', valences: [0],          covalentRadius: 1.40, atomicMass: 131.293, electronegativity: 2.60, category: 'noble-gas' },
  { atomicNumber: 55, symbol: 'Cs', name: 'Cesium',         cpkColor: '#57178F', valences: [1],          covalentRadius: 2.44, atomicMass: 132.905, electronegativity: 0.79, category: 'alkali-metal' },
  { atomicNumber: 56, symbol: 'Ba', name: 'Barium',         cpkColor: '#00C900', valences: [2],          covalentRadius: 2.15, atomicMass: 137.327, electronegativity: 0.89, category: 'alkaline-earth' },
  { atomicNumber: 57, symbol: 'La', name: 'Lanthanum',      cpkColor: '#70D4FF', valences: [3],          covalentRadius: 2.07, atomicMass: 138.905, electronegativity: 1.10, category: 'lanthanide' },
  { atomicNumber: 58, symbol: 'Ce', name: 'Cerium',         cpkColor: '#FFFFC7', valences: [3, 4],       covalentRadius: 2.04, atomicMass: 140.116, electronegativity: 1.12, category: 'lanthanide' },
  { atomicNumber: 59, symbol: 'Pr', name: 'Praseodymium',   cpkColor: '#D9FFC7', valences: [3],          covalentRadius: 2.03, atomicMass: 140.908, electronegativity: 1.13, category: 'lanthanide' },
  { atomicNumber: 60, symbol: 'Nd', name: 'Neodymium',      cpkColor: '#C7FFC7', valences: [3],          covalentRadius: 2.01, atomicMass: 144.242, electronegativity: 1.14, category: 'lanthanide' },
  { atomicNumber: 61, symbol: 'Pm', name: 'Promethium',     cpkColor: '#A3FFC7', valences: [3],          covalentRadius: 1.99, atomicMass: 145.0,   electronegativity: 1.13, category: 'lanthanide' },
  { atomicNumber: 62, symbol: 'Sm', name: 'Samarium',       cpkColor: '#8FFFC7', valences: [3],          covalentRadius: 1.98, atomicMass: 150.36,  electronegativity: 1.17, category: 'lanthanide' },
  { atomicNumber: 63, symbol: 'Eu', name: 'Europium',       cpkColor: '#61FFC7', valences: [3],          covalentRadius: 1.98, atomicMass: 151.964, electronegativity: 1.20, category: 'lanthanide' },
  { atomicNumber: 64, symbol: 'Gd', name: 'Gadolinium',     cpkColor: '#45FFC7', valences: [3],          covalentRadius: 1.96, atomicMass: 157.25,  electronegativity: 1.20, category: 'lanthanide' },
  { atomicNumber: 65, symbol: 'Tb', name: 'Terbium',        cpkColor: '#30FFC7', valences: [3],          covalentRadius: 1.94, atomicMass: 158.925, electronegativity: 1.10, category: 'lanthanide' },
  { atomicNumber: 66, symbol: 'Dy', name: 'Dysprosium',     cpkColor: '#1FFFC7', valences: [3],          covalentRadius: 1.92, atomicMass: 162.500, electronegativity: 1.22, category: 'lanthanide' },
  { atomicNumber: 67, symbol: 'Ho', name: 'Holmium',        cpkColor: '#00FF9C', valences: [3],          covalentRadius: 1.92, atomicMass: 164.930, electronegativity: 1.23, category: 'lanthanide' },
  { atomicNumber: 68, symbol: 'Er', name: 'Erbium',         cpkColor: '#00E675', valences: [3],          covalentRadius: 1.89, atomicMass: 167.259, electronegativity: 1.24, category: 'lanthanide' },
  { atomicNumber: 69, symbol: 'Tm', name: 'Thulium',        cpkColor: '#00D452', valences: [3],          covalentRadius: 1.90, atomicMass: 168.934, electronegativity: 1.25, category: 'lanthanide' },
  { atomicNumber: 70, symbol: 'Yb', name: 'Ytterbium',      cpkColor: '#00BF38', valences: [3],          covalentRadius: 1.87, atomicMass: 173.045, electronegativity: 1.10, category: 'lanthanide' },
  { atomicNumber: 71, symbol: 'Lu', name: 'Lutetium',       cpkColor: '#00AB24', valences: [3],          covalentRadius: 1.87, atomicMass: 174.967, electronegativity: 1.27, category: 'lanthanide' },
  { atomicNumber: 72, symbol: 'Hf', name: 'Hafnium',        cpkColor: '#4DC2FF', valences: [4],          covalentRadius: 1.75, atomicMass: 178.49,  electronegativity: 1.30, category: 'transition-metal' },
  { atomicNumber: 73, symbol: 'Ta', name: 'Tantalum',       cpkColor: '#4DA6FF', valences: [5],          covalentRadius: 1.70, atomicMass: 180.948, electronegativity: 1.50, category: 'transition-metal' },
  { atomicNumber: 74, symbol: 'W',  name: 'Tungsten',       cpkColor: '#2194D6', valences: [6],          covalentRadius: 1.62, atomicMass: 183.84,  electronegativity: 2.36, category: 'transition-metal' },
  { atomicNumber: 75, symbol: 'Re', name: 'Rhenium',        cpkColor: '#267DAB', valences: [7],          covalentRadius: 1.51, atomicMass: 186.207, electronegativity: 1.90, category: 'transition-metal' },
  { atomicNumber: 76, symbol: 'Os', name: 'Osmium',         cpkColor: '#266696', valences: [4],          covalentRadius: 1.44, atomicMass: 190.23,  electronegativity: 2.20, category: 'transition-metal' },
  { atomicNumber: 77, symbol: 'Ir', name: 'Iridium',        cpkColor: '#175487', valences: [3],          covalentRadius: 1.41, atomicMass: 192.217, electronegativity: 2.20, category: 'transition-metal' },
  { atomicNumber: 78, symbol: 'Pt', name: 'Platinum',       cpkColor: '#D0D0E0', valences: [4],          covalentRadius: 1.36, atomicMass: 195.084, electronegativity: 2.28, category: 'transition-metal' },
  { atomicNumber: 79, symbol: 'Au', name: 'Gold',           cpkColor: '#FFD123', valences: [3],          covalentRadius: 1.36, atomicMass: 196.967, electronegativity: 2.54, category: 'transition-metal' },
  { atomicNumber: 80, symbol: 'Hg', name: 'Mercury',        cpkColor: '#B8B8D0', valences: [2],          covalentRadius: 1.32, atomicMass: 200.592, electronegativity: 2.00, category: 'post-transition-metal' },
  { atomicNumber: 81, symbol: 'Tl', name: 'Thallium',       cpkColor: '#A6544D', valences: [3],          covalentRadius: 1.45, atomicMass: 204.383, electronegativity: 1.62, category: 'post-transition-metal' },
  { atomicNumber: 82, symbol: 'Pb', name: 'Lead',           cpkColor: '#575961', valences: [4],          covalentRadius: 1.46, atomicMass: 207.2,   electronegativity: 2.33, category: 'post-transition-metal' },
  { atomicNumber: 83, symbol: 'Bi', name: 'Bismuth',        cpkColor: '#9E4FB5', valences: [3],          covalentRadius: 1.48, atomicMass: 208.980, electronegativity: 2.02, category: 'post-transition-metal' },
  { atomicNumber: 84, symbol: 'Po', name: 'Polonium',       cpkColor: '#AB5C00', valences: [4],          covalentRadius: 1.40, atomicMass: 209.0,   electronegativity: 2.00, category: 'post-transition-metal' },
  { atomicNumber: 85, symbol: 'At', name: 'Astatine',       cpkColor: '#754F45', valences: [1],          covalentRadius: 1.50, atomicMass: 210.0,   electronegativity: 2.20, category: 'halogen' },
  { atomicNumber: 86, symbol: 'Rn', name: 'Radon',          cpkColor: '#428296', valences: [0],          covalentRadius: 1.50, atomicMass: 222.0,   electronegativity: null, category: 'noble-gas' },
  { atomicNumber: 87, symbol: 'Fr', name: 'Francium',       cpkColor: '#420066', valences: [1],          covalentRadius: 2.60, atomicMass: 223.0,   electronegativity: 0.70, category: 'alkali-metal' },
  { atomicNumber: 88, symbol: 'Ra', name: 'Radium',         cpkColor: '#007D00', valences: [2],          covalentRadius: 2.21, atomicMass: 226.0,   electronegativity: 0.90, category: 'alkaline-earth' },
  { atomicNumber: 89, symbol: 'Ac', name: 'Actinium',       cpkColor: '#70ABFA', valences: [3],          covalentRadius: 2.15, atomicMass: 227.0,   electronegativity: 1.10, category: 'actinide' },
  { atomicNumber: 90, symbol: 'Th', name: 'Thorium',        cpkColor: '#00BAFF', valences: [4],          covalentRadius: 2.06, atomicMass: 232.038, electronegativity: 1.30, category: 'actinide' },
  { atomicNumber: 91, symbol: 'Pa', name: 'Protactinium',   cpkColor: '#00A1FF', valences: [5],          covalentRadius: 2.00, atomicMass: 231.036, electronegativity: 1.50, category: 'actinide' },
  { atomicNumber: 92, symbol: 'U',  name: 'Uranium',        cpkColor: '#008FFF', valences: [6],          covalentRadius: 1.96, atomicMass: 238.029, electronegativity: 1.38, category: 'actinide' },
  { atomicNumber: 93, symbol: 'Np', name: 'Neptunium',      cpkColor: '#0080FF', valences: [5],          covalentRadius: 1.90, atomicMass: 237.0,   electronegativity: 1.36, category: 'actinide' },
  { atomicNumber: 94, symbol: 'Pu', name: 'Plutonium',      cpkColor: '#006BFF', valences: [4],          covalentRadius: 1.87, atomicMass: 244.0,   electronegativity: 1.28, category: 'actinide' },
  { atomicNumber: 95, symbol: 'Am', name: 'Americium',      cpkColor: '#545CF2', valences: [3],          covalentRadius: 1.80, atomicMass: 243.0,   electronegativity: 1.30, category: 'actinide' },
  { atomicNumber: 96, symbol: 'Cm', name: 'Curium',         cpkColor: '#785CE3', valences: [3],          covalentRadius: 1.69, atomicMass: 247.0,   electronegativity: 1.30, category: 'actinide' },
  { atomicNumber: 97, symbol: 'Bk', name: 'Berkelium',      cpkColor: '#8A4FE3', valences: [3],          covalentRadius: 1.68, atomicMass: 247.0,   electronegativity: 1.30, category: 'actinide' },
  { atomicNumber: 98, symbol: 'Cf', name: 'Californium',    cpkColor: '#A136D4', valences: [3],          covalentRadius: 1.68, atomicMass: 251.0,   electronegativity: 1.30, category: 'actinide' },
  { atomicNumber: 99, symbol: 'Es', name: 'Einsteinium',    cpkColor: '#B31FD4', valences: [3],          covalentRadius: 1.65, atomicMass: 252.0,   electronegativity: 1.30, category: 'actinide' },
  { atomicNumber: 100, symbol: 'Fm', name: 'Fermium',       cpkColor: '#B31FBA', valences: [3],          covalentRadius: 1.67, atomicMass: 257.0,   electronegativity: 1.30, category: 'actinide' },
  { atomicNumber: 101, symbol: 'Md', name: 'Mendelevium',   cpkColor: '#B30DA6', valences: [3],          covalentRadius: 1.73, atomicMass: 258.0,   electronegativity: 1.30, category: 'actinide' },
  { atomicNumber: 102, symbol: 'No', name: 'Nobelium',      cpkColor: '#BD0D87', valences: [3],          covalentRadius: 1.76, atomicMass: 259.0,   electronegativity: 1.30, category: 'actinide' },
  { atomicNumber: 103, symbol: 'Lr', name: 'Lawrencium',    cpkColor: '#C70066', valences: [3],          covalentRadius: 1.61, atomicMass: 262.0,   electronegativity: 1.30, category: 'actinide' },
  { atomicNumber: 104, symbol: 'Rf', name: 'Rutherfordium', cpkColor: '#CC0059', valences: [4],          covalentRadius: 1.57, atomicMass: 265.0,   electronegativity: null, category: 'transition-metal' },
  { atomicNumber: 105, symbol: 'Db', name: 'Dubnium',       cpkColor: '#D1004F', valences: [5],          covalentRadius: 1.49, atomicMass: 268.0,   electronegativity: null, category: 'transition-metal' },
  { atomicNumber: 106, symbol: 'Sg', name: 'Seaborgium',    cpkColor: '#D90045', valences: [6],          covalentRadius: 1.43, atomicMass: 271.0,   electronegativity: null, category: 'transition-metal' },
  { atomicNumber: 107, symbol: 'Bh', name: 'Bohrium',       cpkColor: '#E00038', valences: [7],          covalentRadius: 1.41, atomicMass: 272.0,   electronegativity: null, category: 'transition-metal' },
  { atomicNumber: 108, symbol: 'Hs', name: 'Hassium',       cpkColor: '#E6002E', valences: [8],          covalentRadius: 1.34, atomicMass: 277.0,   electronegativity: null, category: 'transition-metal' },
  { atomicNumber: 109, symbol: 'Mt', name: 'Meitnerium',    cpkColor: '#EB0026', valences: [6],          covalentRadius: 1.29, atomicMass: 276.0,   electronegativity: null, category: 'transition-metal' },
  { atomicNumber: 110, symbol: 'Ds', name: 'Darmstadtium',  cpkColor: '#EB0026', valences: [6],          covalentRadius: 1.28, atomicMass: 281.0,   electronegativity: null, category: 'transition-metal' },
  { atomicNumber: 111, symbol: 'Rg', name: 'Roentgenium',   cpkColor: '#EB0026', valences: [3],          covalentRadius: 1.21, atomicMass: 282.0,   electronegativity: null, category: 'transition-metal' },
  { atomicNumber: 112, symbol: 'Cn', name: 'Copernicium',   cpkColor: '#EB0026', valences: [2],          covalentRadius: 1.22, atomicMass: 285.0,   electronegativity: null, category: 'transition-metal' },
  { atomicNumber: 113, symbol: 'Nh', name: 'Nihonium',      cpkColor: '#EB0026', valences: [3],          covalentRadius: 1.36, atomicMass: 286.0,   electronegativity: null, category: 'post-transition-metal' },
  { atomicNumber: 114, symbol: 'Fl', name: 'Flerovium',     cpkColor: '#EB0026', valences: [4],          covalentRadius: 1.43, atomicMass: 289.0,   electronegativity: null, category: 'post-transition-metal' },
  { atomicNumber: 115, symbol: 'Mc', name: 'Moscovium',     cpkColor: '#EB0026', valences: [3],          covalentRadius: 1.62, atomicMass: 290.0,   electronegativity: null, category: 'post-transition-metal' },
  { atomicNumber: 116, symbol: 'Lv', name: 'Livermorium',   cpkColor: '#EB0026', valences: [4],          covalentRadius: 1.75, atomicMass: 293.0,   electronegativity: null, category: 'post-transition-metal' },
  { atomicNumber: 117, symbol: 'Ts', name: 'Tennessine',    cpkColor: '#EB0026', valences: [1],          covalentRadius: 1.65, atomicMass: 294.0,   electronegativity: null, category: 'halogen' },
  { atomicNumber: 118, symbol: 'Og', name: 'Oganesson',     cpkColor: '#EB0026', valences: [0],          covalentRadius: 1.57, atomicMass: 294.0,   electronegativity: null, category: 'noble-gas' },
];

export const ELEMENTS_BY_SYMBOL = new Map<string, ElementData>(
  ELEMENTS.map(e => [e.symbol, e])
);

export const ELEMENTS_BY_NUMBER = new Map<number, ElementData>(
  ELEMENTS.map(e => [e.atomicNumber, e])
);

export const PERIODIC_TABLE_LAYOUT: (number | null)[][] = [
  [1,  null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 2],
  [3,  4,    null, null, null, null, null, null, null, null, null, null, 5,   6,   7,   8,   9,   10],
  [11, 12,   null, null, null, null, null, null, null, null, null, null, 13,  14,  15,  16,  17,  18],
  [19, 20,   21,   22,   23,   24,   25,   26,   27,   28,   29,   30,   31,  32,  33,  34,  35,  36],
  [37, 38,   39,   40,   41,   42,   43,   44,   45,   46,   47,   48,   49,  50,  51,  52,  53,  54],
  [55, 56,   null, 72,   73,   74,   75,   76,   77,   78,   79,   80,   81,  82,  83,  84,  85,  86],
  [87, 88,   null, 104,  105,  106,  107,  108,  109,  110,  111,  112,  113, 114, 115, 116, 117, 118],
  [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
  [null, null, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, null],
  [null, null, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, null],
];
