import { FragmentDef } from '../models';

const hex = (k: number, r = 52) => ({
  dx: Math.round(r * Math.cos((k * 60 - 90) * Math.PI / 180)),
  dy: Math.round(r * Math.sin((k * 60 - 90) * Math.PI / 180)),
});

export const FRAGMENTS: FragmentDef[] = [
  // ── Row 1 ────────────────────────────────────────────────────────────────
  {
    id: 'hydroxyl',
    label: '-OH',
    description: 'Hydroxyl group',
    anchorColor: '#FF0D0D',
    unlockedBySmarts: '[OH]',
    unlockedByHint: 'any molecule with an O-H group',
    atoms: [
      { symbol: 'O', dx: 0, dy: 0   },
      { symbol: 'H', dx: 0, dy: -45 },
    ],
    bonds: [{ from: 0, to: 1, type: 'single' }],
  },
  {
    id: 'thiol',
    label: '-SH',
    description: 'Thiol (sulfhydryl) group',
    anchorColor: '#FFFF30',
    unlockedBySmarts: '[SH]',
    unlockedByHint: 'any molecule with an S-H group',
    atoms: [
      { symbol: 'S', dx: 0, dy: 0   },
      { symbol: 'H', dx: 0, dy: -46 },
    ],
    bonds: [{ from: 0, to: 1, type: 'single' }],
  },
  {
    id: 'methyl',
    label: '-CH₃',
    description: 'Methyl group',
    anchorColor: '#909090',
    unlockedBySmarts: '[CH3]',
    unlockedByHint: 'any molecule with a C-H₃ group',
    atoms: [
      { symbol: 'C', dx: 0,   dy: 0   },
      { symbol: 'H', dx: 0,   dy: -46 },
      { symbol: 'H', dx: -40, dy: 23  },
      { symbol: 'H', dx: 40,  dy: 23  },
    ],
    bonds: [
      { from: 0, to: 1, type: 'single' },
      { from: 0, to: 2, type: 'single' },
      { from: 0, to: 3, type: 'single' },
    ],
  },
  {
    id: 'methylene',
    label: '-CH₂-',
    description: 'Methylene bridge — connects two atoms',
    anchorColor: '#909090',
    unlockedBySmarts: '[CH2]',
    unlockedByHint: 'any molecule with a -CH₂- group',
    atoms: [
      { symbol: 'C', dx: 0,   dy: 0   },
      { symbol: 'H', dx: -32, dy: -40 },
      { symbol: 'H', dx: 32,  dy: -40 },
    ],
    bonds: [
      { from: 0, to: 1, type: 'single' },
      { from: 0, to: 2, type: 'single' },
    ],
  },
  {
    id: 'amino',
    label: '-NH₂',
    description: 'Amino group',
    anchorColor: '#3050F8',
    unlockedBySmarts: '[NH2]',
    unlockedByHint: 'any molecule with an N-H₂ group',
    atoms: [
      { symbol: 'N', dx: 0,   dy: 0   },
      { symbol: 'H', dx: -28, dy: -38 },
      { symbol: 'H', dx: 28,  dy: -38 },
    ],
    bonds: [
      { from: 0, to: 1, type: 'single' },
      { from: 0, to: 2, type: 'single' },
    ],
  },

  {
    id: 'imine',
    label: '-NH-',
    description: 'Secondary amine bridge — connects two atoms via nitrogen',
    anchorColor: '#3050F8',
    unlockedBySmarts: '[NH]',
    unlockedByHint: 'any molecule with a secondary N-H group',
    atoms: [
      { symbol: 'N', dx: 0, dy: 0   },
      { symbol: 'H', dx: 0, dy: -40 },
    ],
    bonds: [{ from: 0, to: 1, type: 'single' }],
  },

  // ── Row 2 ────────────────────────────────────────────────────────────────
  {
    id: 'alkene',
    label: 'C=C',
    description: 'Alkene — carbon double bond',
    anchorColor: '#909090',
    unlockedBySmarts: 'C=C',
    unlockedByHint: 'any molecule with a C=C double bond',
    atoms: [
      { symbol: 'C', dx: -26, dy: 0 },
      { symbol: 'C', dx: 26,  dy: 0 },
    ],
    bonds: [{ from: 0, to: 1, type: 'double' }],
  },
  {
    id: 'carbonyl',
    label: 'C=O',
    description: 'Carbonyl group',
    anchorColor: '#909090',
    unlockedBySmarts: '[#6]=[#8]',
    unlockedByHint: 'any molecule with a C=O bond',
    atoms: [
      { symbol: 'C', dx: 0, dy: 0   },
      { symbol: 'O', dx: 0, dy: -52 },
    ],
    bonds: [{ from: 0, to: 1, type: 'double' }],
  },
  {
    id: 'alkyne',
    label: 'C≡C',
    description: 'Alkyne — carbon triple bond',
    anchorColor: '#909090',
    unlockedBySmarts: 'C#C',
    unlockedByHint: 'any molecule with a C≡C triple bond',
    atoms: [
      { symbol: 'C', dx: -26, dy: 0 },
      { symbol: 'C', dx: 26,  dy: 0 },
    ],
    bonds: [{ from: 0, to: 1, type: 'triple' }],
  },
  {
    id: 'nitrile',
    label: '-C≡N',
    description: 'Nitrile (cyano) group',
    anchorColor: '#909090',
    unlockedBySmarts: 'C#N',
    unlockedByHint: 'any molecule with a C≡N triple bond',
    atoms: [
      { symbol: 'C', dx: -26, dy: 0 },
      { symbol: 'N', dx: 26,  dy: 0 },
    ],
    bonds: [{ from: 0, to: 1, type: 'triple' }],
  },
  {
    id: 'carboxyl',
    label: '-COOH',
    description: 'Carboxyl group',
    anchorColor: '#909090',
    unlockedBySmarts: '[CX3](=[OX1])[OX2H1]',
    unlockedByHint: 'any molecule with a -COOH group',
    atoms: [
      { symbol: 'C', dx: 0,  dy: 0   },
      { symbol: 'O', dx: 0,  dy: -52 },
      { symbol: 'O', dx: 52, dy: 0   },
      { symbol: 'H', dx: 97, dy: 0   },
    ],
    bonds: [
      { from: 0, to: 1, type: 'double' },
      { from: 0, to: 2, type: 'single' },
      { from: 2, to: 3, type: 'single' },
    ],
  },
  {
    id: 'benzene',
    label: 'C₆H₆',
    description: 'Benzene ring',
    anchorColor: '#909090',
    unlockedBySmarts: 'c1ccccc1',
    unlockedByHint: 'any molecule with a benzene ring',
    atoms: [
      { symbol: 'C', ...hex(0) },
      { symbol: 'C', ...hex(1) },
      { symbol: 'C', ...hex(2) },
      { symbol: 'C', ...hex(3) },
      { symbol: 'C', ...hex(4) },
      { symbol: 'C', ...hex(5) },
      { symbol: 'H', ...hex(0, 97) },
      { symbol: 'H', ...hex(1, 97) },
      { symbol: 'H', ...hex(2, 97) },
      { symbol: 'H', ...hex(3, 97) },
      { symbol: 'H', ...hex(4, 97) },
      { symbol: 'H', ...hex(5, 97) },
    ],
    bonds: [
      { from: 0, to: 1, type: 'double' },
      { from: 1, to: 2, type: 'single' },
      { from: 2, to: 3, type: 'double' },
      { from: 3, to: 4, type: 'single' },
      { from: 4, to: 5, type: 'double' },
      { from: 5, to: 0, type: 'single' },
      { from: 0, to: 6,  type: 'single' },
      { from: 1, to: 7,  type: 'single' },
      { from: 2, to: 8,  type: 'single' },
      { from: 3, to: 9,  type: 'single' },
      { from: 4, to: 10, type: 'single' },
      { from: 5, to: 11, type: 'single' },
    ],
  },
];
